# Generated by Django 3.1.4 on 2021-01-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('wallet_addr', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_state', models.CharField(max_length=1000)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
