# Generated by Django 3.1.4 on 2021-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto2048', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='game_state',
            new_name='gamestate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='wallet_addr',
            new_name='wltaddr',
        ),
    ]
